#Used for Visualization

minimap: "map/mymapv10.png"

results:
  jsonl: "results/tracks2.jsonl"

cam1:
  src_pts:
    - [3, 549]
    - [190, 451]
    - [352, 539]
    - [109, 717]
  dst_pts:
    - [175, 263]
    - [371, 262]
    - [384, 403]
    - [184, 409]

cam2:
  src_pts:
    - [37, 412]
    - [340, 399]
    - [386, 670]
    - [21, 668]
  dst_pts:
    - [445, 180]
    - [442, 44]
    - [673, 44]
    - [667, 185]